/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package anaskfinancialtracker;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author aamir
 */
public class inventoryadd extends javax.swing.JFrame {
    private String fullname;

    /**
     */
    public inventoryadd(String fullname) {
                this.fullname = fullname; // Initialize the member variable with the passed value

        initComponents();
        Timer timer = new Timer(100, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                updateDateTime();
            }
        });
        timer.start();
    }

    private inventoryadd() {
    }


   
  private void updateDateTime() {
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
        Date date = new Date();
        dateTimeLabel.setText(formatter.format(date));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itemBtn = new javax.swing.JPanel();
        amountLbl = new javax.swing.JLabel();
        itemLbl = new javax.swing.JLabel();
        itemTxt = new javax.swing.JTextField();
        amountTxt = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        titleLbl = new javax.swing.JLabel();
        sellLbl = new javax.swing.JLabel();
        priceTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        cogsLbl = new javax.swing.JLabel();
        cogsTxt = new javax.swing.JTextField();
        dateTimeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        itemBtn.setBackground(new java.awt.Color(0, 0, 0));

        amountLbl.setFont(new java.awt.Font("Avenir Next Condensed", 0, 18)); // NOI18N
        amountLbl.setForeground(new java.awt.Color(255, 255, 255));
        amountLbl.setText("Quantity of Products");

        itemLbl.setFont(new java.awt.Font("Avenir Next Condensed", 0, 18)); // NOI18N
        itemLbl.setForeground(new java.awt.Color(255, 255, 255));
        itemLbl.setText("Item Name");

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        titleLbl.setFont(new java.awt.Font("Avenir Next Condensed", 1, 48)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(0, 255, 204));
        titleLbl.setText("ADD PRODUCTS");

        sellLbl.setFont(new java.awt.Font("Avenir Next Condensed", 0, 18)); // NOI18N
        sellLbl.setForeground(new java.awt.Color(255, 255, 255));
        sellLbl.setText("Selling Price");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cogsLbl.setFont(new java.awt.Font("Avenir Next Condensed", 0, 18)); // NOI18N
        cogsLbl.setForeground(new java.awt.Color(255, 255, 255));
        cogsLbl.setText("Cost of Product");

        dateTimeLabel.setBackground(new java.awt.Color(255, 255, 255));
        dateTimeLabel.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout itemBtnLayout = new javax.swing.GroupLayout(itemBtn);
        itemBtn.setLayout(itemBtnLayout);
        itemBtnLayout.setHorizontalGroup(
            itemBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemBtnLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(titleLbl)
                .addGap(36, 36, 36)
                .addComponent(dateTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(itemBtnLayout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addGroup(itemBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(amountLbl)
                    .addGroup(itemBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cogsTxt)
                        .addComponent(priceTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addComponent(amountTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addComponent(itemTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(itemBtnLayout.createSequentialGroup()
                .addGroup(itemBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(itemBtnLayout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(cogsLbl))
                    .addGroup(itemBtnLayout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(addBtn))
                    .addGroup(itemBtnLayout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(sellLbl))
                    .addGroup(itemBtnLayout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(itemLbl)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        itemBtnLayout.setVerticalGroup(
            itemBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemBtnLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(itemBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(itemBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dateTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(itemLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(itemTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(amountLbl)
                .addGap(18, 18, 18)
                .addComponent(amountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sellLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(priceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cogsLbl)
                .addGap(18, 18, 18)
                .addComponent(cogsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(addBtn)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(itemBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(itemBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
      try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        String url = "jdbc:mysql://localhost:3306/anaskdatabase?zeroDateTimeBehavior=CONVERT_TO_NULL";
        Connection con = DriverManager.getConnection(url, "root", "Mysqldatabase101");
        con.setAutoCommit(false); // Start transaction
        Statement st = con.createStatement();
        String item = itemTxt.getText();
        String amountstr = amountTxt.getText();
        String pricestr = priceTxt.getText();
        String cogsstr = cogsTxt.getText();

        int cogs = Integer.parseInt(cogsstr);
        int amount = Integer.parseInt(amountstr);
        int price = Integer.parseInt(pricestr);

        // Insert the new product into inventory
        String query = "INSERT INTO inventory (item, amount, price, expenses, sold) VALUES ('" + item + "', " + amount + ", " + price + ", " + cogs + ", 0);";
        int rowsAffected = st.executeUpdate(query);

        if (rowsAffected > 0) {
            // Calculate additional costs and potential profit
            int additionalCost = cogs * amount;
            int potentialProfit = (price - cogs) * amount;

            // Update the COGS in the finance table
            String updateCOGS = "UPDATE finance SET Amount = Amount + " + additionalCost + " WHERE Name='Cost of Goods';";
            st.executeUpdate(updateCOGS);

            // Update Potential Profit in the finance table
            String updateProfit = "UPDATE finance SET Amount = Amount + " + potentialProfit + " WHERE Name='Potential Profit';";
            st.executeUpdate(updateProfit);

            con.commit(); // Commit transaction if all updates are successful
            JOptionPane.showMessageDialog(null, "Item and financial data updated successfully.");
        } else {
            JOptionPane.showMessageDialog(null, "Failed to add the item.", "Error", JOptionPane.ERROR_MESSAGE);
            con.rollback(); // Rollback transaction
        }

        st.close();
        con.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "An error occurred: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }

      
      
        
        
        
        
    }//GEN-LAST:event_addBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        inventory inv = new inventory(fullname);
        inv.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inventoryadd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inventoryadd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inventoryadd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inventoryadd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inventoryadd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel amountLbl;
    private javax.swing.JTextField amountTxt;
    private javax.swing.JLabel cogsLbl;
    private javax.swing.JTextField cogsTxt;
    private javax.swing.JLabel dateTimeLabel;
    private javax.swing.JPanel itemBtn;
    private javax.swing.JLabel itemLbl;
    private javax.swing.JTextField itemTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField priceTxt;
    private javax.swing.JLabel sellLbl;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
